version: "2.0"

services:
  render-node:
    build:
      context: ./render
      args:
         NDVIZHOST : $HOSTNAME
         NDVIZPORT : 8001
    volumes:
        - /nas:/nas:ro
        - /nas2:/nas2:ro
        - /nas3:/nas3:ro
        - /nas4:/nas4:ro
    ports:
        - 8080
    logging:
        driver: "syslog"
        options:
           syslog-address: "udp://localhost:514"
           tag: "render-node"
    environment:
        - NDVIZHOST:$HOSTNAME:8001

