- name: Deploy render web service
  hosts: renderboxes
  tasks:
    - name: Get the render-ws image
      docker_image:
        name: docker.aibs-artifactory.corp.alleninstitute.org/fcollman/render-ws
        tag: "{{ws_tag}}"
        state: present
        force: yes
        pull: yes
    - name: Launch render-ws service
      docker_service:
        recreate: always
        project_name: "{{compose_project}}"
        state: present
        debug: yes
        definition:
          version: "2.0"
          services:
            render:
                image: "docker.aibs-artifactory.corp.alleninstitute.org/fcollman/render-ws:{{ws_tag}}"
                ports:
                  - "{{ws_port}}:8080"
                environment:
                  - MONGO_HOST=mongo
                  - MONGO_PORT=27017
                  - NDVIZHOST="{{ndviz_host}}"
                  - NDVIZPORT="{{ndviz_port}}"
                  - JAVA_OPTIONS="{{ lookup('env','JAVA_OPTIONS') }}""
                depends_on:
                    - mongo
            mongo:
                image: mongo:3.4.2
                expose:
                    - "27017"
                volumes:
                    - "{{db_path}}:/data/db"
                restart: always
                security_opt:
                  - seccomp:unconfined
      register: output
    - debug:
        var: output
