- name: Deploy render web service
  hosts: renderboxes
  tasks:
    - name: Get the render-ws image
      docker_image:
        name: docker.aibs-artifactory.corp.alleninstitute.org/fcollman/render-ws
        tag: "{{ lookup('env','RENDER_WS_TAG') }}"
        state: present
        force: yes
        pull: yes
    - name: Launch render-ws service
      docker_service:
        recreate: always
        project_name: render-ws
        state: present
        definition:
          version: "2.0"
          services:
          render:
              build: ./render
              ports:
                - "{{ lookup('env','RENDER_WS_PORT') }}:8080"
              env:
                - MONGO_HOST=mongo
                - MONGO_PORT=27017
              depends_on:
                  - mongo
          mongo:
              image: mongo:3.4.2
              expose:
                  - "27017"
              volumes:
                  - "{{ lookup('env','RENDER_DBPATH') }}:/data/db"
              restart: always
              security_opt:
                - seccomp:unconfined
